#!/bin/sh
#
# Testing script for students to compare output with the example outputs
#
# Student: execute this script to compare your output with the examples.
#
# Note: does NOT save and compare stderr, because the test programs for
# this assignment should not be writing anything to stderr

n=1
while [ -f ./str_test$n ]
do
	echo Running test $n
	./str_test$n > out.$n
	echo cmp stdout.$n out.$n
	cmp stdout.$n out.$n
	n=`expr $n + 1`
done
